title: Marco Rocha
logo: /img/perfil.jfif
description: | 
  I am an enthusiast in the world of data science and analytics. 
  My passion lies in transforming data into meaningful insights. 
  With skills in Python and SQL, along with experience in tools like Power BI and Excel, I continually seek opportunities to apply my knowledge to challenging projects.
# show_downloads: True
theme: jekyll-theme-minimal
